blog/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

#
app_name = 'blog'
urlpatterns = [
    #as_view方法把一个类转成一个函数
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$',login_required(views.PostDetailView.as_view()),name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesView.as_view(),name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$',views.TagView.as_view(),name='tag'),
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'',include('comments.urls')),
    url(r'^accounts/',include('users.urls')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
]

comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$',views.post_comment,name='post_comment'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200,blank=True)
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag,blank=True)
    author = models.ForeignKey(User)
    #PositiveIntegerField类型只允许为正整数或0
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})

    class Meta:
        ordering=['-created_time']

    def increase_views(self):
        self.views += 1
        #update_fields数据库只更新views字段的值，提高效率
        self.save(update_fields=['views'])

comments/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    #作用是当评论保存到数据库的时候，自动把时间的值指定为当前时间
    created_time = models.DateTimeField(auto_now_add=True)
    #这个评论是关联到某篇文章（Post）
    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

blog/views.py
import markdown
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from comments.forms import CommentForm
# Create your views here.
from blog.models import Post, Category, Tag
from django.views.generic import ListView,DetailView

'''
def index(request):
    post_list = Post.objects.all()

    return render(request,'blog/index.html',context={'post_list':post_list})
 
 
 def category(request,pk):
    cate = get_object_or_404(Category,pk=pk)
    post_list = Post.objects.filter(category=cate)
    return render(request,'blog/index.html',context={'post_list':post_list})

def archives(request,year,month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month)
    return render(request,'blog/index.html',context={'post_list':post_list})
 
'''
#对于这种获取某个表的列表数据的，就用ListView类视图
class IndexView(ListView):
    #model:告诉django要获取哪个模型类的数据，就是获取哪个表的数据
    model = Post
    #指定要渲染的模板
    template_name = 'blog/index.html'
    #获取数据的变量名，这个变量会传递给模板
    context_object_name = 'post_list'
    #类视图帮我们分页逻辑，通过paginate_by指定每页的数量
    paginate_by = 3


class CategoryView(IndexView):
    #和IndexView不用的地方是，我们覆写了父类的get_queryset方法
    #该方法默认获取全部的数据
    #我们只需要获取指定分类下的数据，所以，我们改变的它的默认行为
    #在类视图中，从URL获取的参数值会自动保存在实例的kwargs属性中
    #kwargs是一个字典，args属性是一个列表
    def get_queryset(self):
        cate = get_object_or_404(Category,pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(category=cate)


class ArchivesView(IndexView):
    def get_queryset(self):
        return super().get_queryset().filter(
            created_time__year = self.kwargs.get('year'),
            created_time__month=self.kwargs.get('month'),
        )
'''
listview总结：
1、listview主要用在获取某个model列表中
2、通过template_name属性来指定需要渲染的模板，通过
context_object_name属性来制定需要获取的model列表的名字
3、复写 get_queryset 方法以增加获取model列表的其他逻辑
4、复写get_context_data方法来为上下文对象添加额外的变量以便在模板中访问

'''





'''
def detail(request,pk):
    post = get_object_or_404(Post,pk=pk)
    #阅读量
    post.increase_views()

    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])


    form = CommentForm()
    comment_list = post.comment_set.all()
    context = {'post':post,
               'form':form,
               'comment_list':comment_list}
    return render(request,'blog/detail.html',context=context)

'''

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    #先调用父类的get方法，是因为只有当get方法被调用后，
    # 才有self.object属性，
    # 这个属性就是Post模型的实例
    def get(self, request, *args, **kwargs):

        response = super().get(request,*args,**kwargs)

        self.object.increase_views()

        return response

    def get_object(self, queryset=None):
        post = super().get_object(queryset=None)
        post.body = markdown.markdown(post.body,
                                      extensions=[
                                          'markdown.extensions.extra',
                                          'markdown.extensions.codehilite',
                                          'markdown.extensions.toc',
                                      ])
        return post

    #覆写get_context_data是因为要添加出了post传递的值以外，
    #还需要把评论和表单的内容传递给模板，
    #往context里面添加内容
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({'form':form,
                        'comment_list':comment_list
                        })
        return context

'''
detailview总结:
detailview用来获取某个model中的单个对象
通过template_name属性来指定需要渲染的模板，通过
context_object_name来指定获取的model对象的名字，
复写get_object方法来增加获取对象的其他逻辑
复写get_context_data方法来为上下文对象添加额外的变量，来在模板中访问


'''


class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag,pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(tags=tag)

templates/blog/detail.html
{% extends 'base.html' %}
    {% block main %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">{{ post.title }}</h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                    <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
               {{ post.body|safe }}
            </div>
        </article>

        <section class="comment-area" id="comment-area">
            <hr>
            <h3>发表评论</h3>
            <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-4">
                        {# id_for_label就是在你的name前面加个id #}
                        <label for="{{ form.name.id_for_label }}">名字：</label>
                        {{ form.name }}
                        {{ form.name.errors }}
                    </div>
                    <div class="col-md-4">
                        <label for="{{ form.email.id_for_label }}">邮箱：</label>
                        {{ form.email }}
                        {{ form.email.errors }}
                    </div>
                    <div class="col-md-4">
                        <label for="{{ form.url.id_for_label }}">网址：</label>
                        {{ form.url }}
                        {{ form.url.errors }}
                    </div>
                    <div class="col-md-12">
                        <label for="{{ form.text.id_for_label }}">评论：</label>
                        {{ form.text }}
                        {{ form.text.errors }}
                        <button type="submit" class="comment-btn">发表</button>
                    </div>
                </div>    <!-- row -->
            </form>
            <div class="comment-list-panel">
                <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                <ul class="comment-list list-unstyled">
                    {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date">{{ comment.created_time }}</time>
                        <div class="text">
                           {{ comment.text }}
                        </div>
                    </li>
                    {% empty %}
                        暂无评论~~
                    {% endfor %}
                </ul>
            </div>
        </section>
    {% endblock main %}
    {% block toc %}
        <div class="widget widget-content">
            <h3 class="widget-title">文章目录</h3>
            <ul>
                <li>
                    <a href="#">教程特点</a>
                </li>
                <li>
                    <a href="#">谁适合这个教程</a>
                </li>
                <li>
                    <a href="#">在线预览</a>
                </li>
                <li>
                    <a href="#">资源列表</a>
                </li>
                <li>
                    <a href="#">获取帮助</a>
                </li>
            </ul>
        </div>
    {% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}

     {% block main %}
        {% for post in post_list %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                    <span class="views-count"><a href="#">{{ post.views }}阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.body|truncatechars:14 }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
        {% empty %}
            <div class="no-post"></div>
        {% endfor %}
         {# is_paginated:判断是都满足分页要求 #}
        {% if is_paginated %}
            <div class="pagination-simple">
                {% if  page_obj.has_previous %}
                     <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                {% endif %}
                <span class="current">第{{ page_obj.number }}页 / 共 {{ paginator.num_pages }} 页</span>
                {% if  page_obj.has_next %}
                     <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                {% endif %}

            </div>

        {% endif %}
         {% comment %}
        <div class="pagination">
            <ul>
                <li><a href="">1</a></li>
                <li><a href="">...</a></li>
                <li><a href="">4</a></li>
                <li><a href="">5</a></li>
                <li class="current"><a href="">6</a></li>
                <li><a href="">7</a></li>
                <li><a href="">8</a></li>
                <li><a href="">...</a></li>
                <li><a href="">11</a></li>
            </ul>
        </div>
        {% endcomment %}
    {% endblock main %}